### ISSUE TITLE
Not getting temperature data for Lower Kootenay River from database

### ISSUE THREAD

**Issue by cdmuir** [poissonconsulting/kootqlt#10]
Only see data from Lower Columbia River at Birchbank and Lower Columbia River at Norns Creek

**Comment by RobynIrvine** [comment]
There is data at LKR_TW from feb 16, 2015 until april 15, 2016. Joe now debugging since I have provided code.

**Comment by joethorley** [comment]
The problem was that it only gets 10,000 rows of data by default - I've adjusted it so that n = Inf by default
